name: piu_util
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  html: ^0.15.4
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/jacket/
    - assets/json/
