name: piu_util
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_debouncer: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  hive: ^2.2.3
  html: ^0.15.4
  image_gallery_saver: ^2.0.3
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  syncfusion_flutter_sliders: ^25.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_oss_licenses: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/avatar/
    - assets/grade/
    - assets/icon/
    - assets/image/
    - assets/jacket/
    - assets/json/
    - assets/plate/
    - assets/step_ball/
    - shorebird.yaml

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
          weight: 400
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600

    - family: Oxanium
      fonts:
        - asset: assets/font/Oxanium-ExtraBold.ttf
